### ISSUE TITLE
Magnifying glass class for images

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#133]
On hover, show built-in magnifying glass:

``` css
img.zoom {
    cursor: -webkit-zoom-in;
    cursor: -moz-zoom-in;
    cursor: zoom-in;
}
```

... or something like that.
