### ISSUE TITLE
Box sizing, border-box!

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#159]
Need to add:

``` css
*,
*::before,
*::after {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
```
