### ISSUE TITLE
Move RG fonts to fonts.registerguard.com

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#190]
So we can link to the CSS styles rather than having to have this in every new project's style sheets:

``` css
/*FONTS*/
@font-face {
    font-family: "BentonSansCond Regular";
    src: url("http://fonts.registerguard.com/benton/sanscondbold.eot");
    src: url("http://fonts.registerguard.com/benton/sanscondbold.eot?#iefix") format("embedded-opentype"),
        url("http://fonts.registerguard.com/benton/sanscondbold.woff") format("woff"),
        url("http://fonts.registerguard.com/benton/sanscondbold.ttf") format("truetype"),
        url("http://fonts.registerguard.com/benton/sanscondbold.svg#web") format("svg");
    font-style: normal;
    font-weight: bold;
}

@font-face {
    font-family: "MillerHeadline Bold";
    src: url("http://fonts.registerguard.com/miller/headlinebold.eot");
    src: url("http://fonts.registerguard.com/miller/headlinebold.eot?#iefix") format("embedded-opentype"),
        url("http://fonts.registerguard.com/miller/headlinebold.woff") format("woff"),
        url("http://fonts.registerguard.com/miller/headlinebold.ttf") format("truetype"),
        url("http://fonts.registerguard.com/miller/headlinebold.svg#web") format("svg");
    font-style: normal;
    font-weight: bold;
}

@font-face {
    font-family: "MillerHeadline Light";
    src: url("http://fonts.registerguard.com/miller/headlinelight.eot");
    src: url("http://fonts.registerguard.com/miller/headlinelight.eot?#iefix") format("embedded-opentype"),
        url("http://fonts.registerguard.com/miller/headlinelight.woff") format("woff"),
        url("http://fonts.registerguard.com/miller/headlinelight.ttf") format("truetype"),
        url("http://fonts.registerguard.com/miller/headlinelight.svg#web") format("svg");
    font-style: normal;
    font-weight: normal;
}

@font-face {
    font-family:"RGWeb";
    src:url("http://fonts.registerguard.com/rg/rgweb.eot");
    src:url("http://fonts.registerguard.com/rg/rgweb.eot?#iefix") format("embedded-opentype"),
        url("http://fonts.registerguard.com/rg/rgweb.woff") format("woff"),
        url("http://fonts.registerguard.com/rg/rgweb.ttf") format("truetype"),
        url("http://fonts.registerguard.com/rg/rgweb.svg#RGWeb") format("svg");
    font-weight:normal;font-style:normal;
}
```
