### ISSUE TITLE
Change banner ID/class names?

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#27]
Put in base and call bd_banner?

``` css
#banner_top { border-bottom: 1px solid #ccc; }
#banner_bottom { border-top: 1px solid #ccc; }
.banner { padding: 5px 0; }
    .banner .advert { margin: 0 auto; } /* Move elsewhere? */
@media only screen and (min-width: 665px) {
    .banner { padding: 10px 0; }
}
```
