### ISSUE TITLE
Re-think BodyText style font-size handling

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#41]
I made `BodyText` style default to the larger font size; I was thinking it was easier to make not say:

``` css
#story p { font-size: 18px; }
```

... for example.

The specificity of the above causes headaches for when it comes to styling InCopy stuff.

Need to clean this up.
