### ISSUE TITLE
Ad margin

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#57]
Remove top/bottom margin from `ad_manager.css`:

``` css
.advert {
    text-align: center; /* Oldschool centering technique. */
    position: relative; /* Just in case ad decides to `position: absolute;` without a `position: relative;` parent. */
    margin: .75em auto; /* Putting `auto` here to assist `.advert`s that have a width. */
}
```

Reason why I'm putting in Bulldog's issue's: The spacing is needed if ad is at top of a column; I need to build a more official way of adding margin/padding to columns (perhaps as a Wiffle addon?)
