### ISSUE TITLE
Old IEs: Should we add chrome frame? (sniffing)

### ISSUE THREAD

**Issue by mhulse** [registerguard/bulldog#84]
From [HTML5BP](https://github.com/h5bp/html5-boilerplate):

``` css
/* ==========================================================================
   Chrome Frame prompt
   ========================================================================== */

.chromeframe {
    margin: 0.2em 0;
    background: #ccc;
    color: #000;
    padding: 0.2em 0;
}
```

And the HTML:

``` html
<!--[if lt IE 7]>
<p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate Google Chrome Frame</a> to improve your experience.</p>
<![endif]-->
```

It targets less than IE7. Should we change that so we target IE 8 and below? If so, what should the message say?

Is [Google Chrome Frame](http://www.google.com/chromeframe) compatible with IE 8 and below (wondering if that message would make sense for > IE6 users)?
